import os
import torch
import timm
import pandas as pd
from fastapi import FastAPI, UploadFile, File, BackgroundTasks
from PIL import Image
from sklearn.preprocessing import LabelEncoder
from torchvision import transforms
import io
import json
import trainer # Your new trainer module

app = FastAPI()

# --- CONFIGURATION ---
MODEL_FILE = "model.pth"              
TRAIN_CSV = "butterfly_images.csv"    # Fallback for first run
NAMES_CSV = "sri_lanka_butterflies_245.csv" # English names mapping

print("Loading LepiNet AI...")

# ---------------------------------------------------------
# 1. LOAD CLASSES (DYNAMIC LOGIC)
# ---------------------------------------------------------
# Priority: Check if 'classes.json' exists (Generated by trainer.py).
# If yes, use it. If no, fall back to the CSV (First run).
CLASSES = []

if os.path.exists("classes.json"):
    print("📂 Found classes.json (Dynamic Mode)")
    try:
        with open("classes.json", "r") as f:
            CLASSES = json.load(f)
        print(f"✅ Classes loaded: {len(CLASSES)} species found.")
    except Exception as e:
        print(f"❌ Error reading classes.json: {e}")

# Fallback: If classes.json is missing, use the CSV (Old method)
if not CLASSES:
    print("⚠️ classes.json not found. Falling back to CSV...")
    try:
        df_train = pd.read_csv(TRAIN_CSV)
        le = LabelEncoder()
        le.fit(df_train.iloc[:, 1]) 
        CLASSES = list(le.classes_) 
        print(f"✅ Classes loaded from CSV: {len(CLASSES)} species found.")
    except Exception as e:
        print(f"❌ Error loading training CSV: {e}")

# ---------------------------------------------------------
# 2. LOAD NAMES MAPPING
# ---------------------------------------------------------
try:
    df_names = pd.read_csv(NAMES_CSV)
    # Create dict: {'b001': 'Tailed Jay', ...}
    ID_TO_NAME = dict(zip(df_names['butterfly_id'], df_names['common_name_english']))
    print(f"✅ Names loaded: {len(ID_TO_NAME)} English names found.")
except Exception as e:
    print(f"❌ Error loading names CSV: {e}")
    ID_TO_NAME = {}

# ---------------------------------------------------------
# 3. LOAD MODEL (ROBUST MODE)
# ---------------------------------------------------------
DEVICE = torch.device("cpu") # Hugging Face Free Tier is CPU only

try:
    print(f"🏗️ Building model for {len(CLASSES)} classes...")
    # Create structure matching the CURRENT class count
    model = timm.create_model('mobilenetv4_conv_small.e2400_r224_in1k', pretrained=False, num_classes=len(CLASSES))
    
    if os.path.exists(MODEL_FILE):
        # Load weights
        state_dict = torch.load(MODEL_FILE, map_location=DEVICE)
        
        # strict=False is CRITICAL here. 
        # It allows the app to load partially if there's a slight mismatch 
        # (though ideally, classes.json and model.pth always match).
        model.load_state_dict(state_dict, strict=False)
        print("✅ Model weights loaded successfully!")
    else:
        print("⚠️ Warning: model.pth not found. API will run but predictions will be random.")

    model.to(DEVICE)
    model.eval()

except Exception as e:
    print(f"❌ Error loading model: {e}")

# ---------------------------------------------------------
# 4. TRANSFORMS
# ---------------------------------------------------------
transform = transforms.Compose([
    transforms.Resize((256, 256)),
    transforms.CenterCrop(224),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
])

# ---------------------------------------------------------
# API ENDPOINTS
# ---------------------------------------------------------

@app.get("/")
def home():
    return {
        "status": "running", 
        "classes_count": len(CLASSES),
        "model_loaded": os.path.exists(MODEL_FILE)
    }

@app.post("/predict")
async def predict(file: UploadFile = File(...)):
    if not CLASSES:
        return {"error": "Model classes not loaded properly."}

    try:
        # Read and preprocess image
        image_data = await file.read()
        image = Image.open(io.BytesIO(image_data)).convert('RGB')
        input_tensor = transform(image).unsqueeze(0).to(DEVICE)
        
        # Inference
        with torch.no_grad():
            outputs = model(input_tensor)
            probabilities = torch.nn.functional.softmax(outputs, dim=1)
            confidence, predicted_idx = torch.max(probabilities, 1)
        
        # Decode result
        idx = predicted_idx.item()
        
        # Safety check for index out of bounds
        if idx < len(CLASSES):
            species_id = CLASSES[idx] 
        else:
            return {"error": "Prediction index out of bounds. Model/Classes mismatch."}

        species_name = ID_TO_NAME.get(species_id, species_id)
        conf_score = confidence.item()

        return {
            "species_id": species_id,
            "species_name": species_name,
            "confidence": round(conf_score, 4)
        }
    
    except Exception as e:
        return {"error": str(e)}

@app.post("/retrain")
async def retrain_endpoint(background_tasks: BackgroundTasks, secret: str):
    """
    Triggered by Admin Dashboard. 
    Runs training in background. 
    """
    # 1. Security Check
    # Ensure you set ADMIN_SECRET in Hugging Face Settings
    if secret != os.environ.get("ADMIN_SECRET"):
        return {"error": "Unauthorized. Wrong Secret."}

    # 2. Run in Background
    background_tasks.add_task(trainer.fine_tune_model)
    
    return {"status": "Training started in background. The Space will restart once finished."}